//! Cookie utilities for the login layer.
//!
//! Provides helpers for reading cookies from request headers and constructing
//! login-state cookie names with appropriate security prefixes (`__Host-`,
//! `__Secure-`, or none). Also provides CBOR encoding for the payloads
//! sealed into the session and login-state cookies — CBOR saves ~25–40%
//! over JSON, which matters because session cookies are sent on every
//! authenticated request.
//!
//! If the wire format ever changes, the rollout strategy is the same as for
//! any other key change: in-flight sessions fail to decode, the user is
//! treated as unauthenticated, and the next navigation restarts the login
//! flow. No explicit format-versioning is needed because re-login already
//! recovers gracefully.

use http::header;
use serde::{Serialize, de::DeserializeOwned};

/// Encodes a cookie payload as CBOR. Used for both the session cookie and
/// the login-state cookie before they are AEAD-sealed and base64-encoded.
pub(crate) fn encode_payload<T: Serialize>(
    value: &T,
) -> Result<Vec<u8>, ciborium::ser::Error<std::io::Error>> {
    let mut bytes = Vec::with_capacity(128);
    ciborium::into_writer(value, &mut bytes)?;
    Ok(bytes)
}

/// Decodes a CBOR cookie payload written by [`encode_payload`].
pub(crate) fn decode_payload<T: DeserializeOwned>(
    bytes: &[u8],
) -> Result<T, ciborium::de::Error<std::io::Error>> {
    ciborium::from_reader(bytes)
}

pub(crate) const LOGIN_COOKIE_PREFIX: &str = "huskarl_login_";

/// Maximum accepted length of an OAuth `state` value. Picks a generous bound
/// (256 bytes) since typical states are 16-64 chars of base64url.
pub(crate) const MAX_OAUTH_STATE_LEN: usize = 256;

/// Returns `true` if `state` is safe to splice into a cookie name: non-empty,
/// within [`MAX_OAUTH_STATE_LEN`], and composed only of URL-safe base64url
/// characters (`A-Za-z0-9-_`).
///
/// OAuth state is opaque to the spec but generated by us as URL-safe random
/// bytes; this validator rejects attacker-supplied callbacks that try to
/// inject other characters into the cookie name (which would otherwise just
/// silently fail to match a cookie).
#[must_use]
pub fn is_valid_oauth_state(state: &str) -> bool {
    !state.is_empty()
        && state.len() <= MAX_OAUTH_STATE_LEN
        && state
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
}

/// Returns the login-state cookie name for the given OAuth `state` value,
/// applying the appropriate cookie name prefix based on security settings:
///
/// - `__Host-` when `secure` is `true` and `path` is `"/"` (strongest guarantee)
/// - `__Secure-` when `secure` is `true` and `path` is a sub-path
/// - no prefix when `secure` is `false` (e.g. local HTTP development)
///
/// `state` must satisfy [`is_valid_oauth_state`]. In debug builds, an invalid
/// state will assert; in release builds the resulting cookie name may be
/// malformed but no header injection is possible because the name is later
/// formatted through `HeaderValue::from_str`.
#[must_use]
pub fn login_state_cookie_name(state: &str, secure: bool, path: &str) -> String {
    debug_assert!(
        is_valid_oauth_state(state),
        "login_state_cookie_name called with state that is not URL-safe base64url"
    );
    let prefix = if secure {
        if path == "/" { "__Host-" } else { "__Secure-" }
    } else {
        ""
    };
    format!("{prefix}{LOGIN_COOKIE_PREFIX}{state}")
}

/// Builds the standard cookie attribute string for session cookies.
///
/// Returns `"HttpOnly; SameSite=Lax; Path={path}; Secure"` (or without
/// `Secure` when `secure` is `false`).
#[must_use]
pub fn cookie_attrs(secure: bool, path: &str) -> String {
    let secure = if secure { "; Secure" } else { "" };
    format!("HttpOnly; SameSite=Lax; Path={path}{secure}")
}

/// Extracts a cookie value by name from request headers.
///
/// This is a utility function for [`SessionDriver`](crate::session::SessionDriver)
/// implementations that need to read cookies from request headers.
pub fn get_cookie<'a>(headers: &'a http::HeaderMap, name: &str) -> Option<&'a str> {
    for value in headers.get_all(header::COOKIE) {
        let Ok(s) = value.to_str() else { continue };
        for pair in s.split(';') {
            if let Some((k, v)) = pair.trim().split_once('=')
                && k.trim() == name
            {
                return Some(v.trim());
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn get_cookie_present() {
        let mut headers = http::HeaderMap::new();
        headers.insert(header::COOKIE, "foo=bar".parse().unwrap());
        assert_eq!(get_cookie(&headers, "foo"), Some("bar"));
    }

    #[test]
    fn get_cookie_missing() {
        let mut headers = http::HeaderMap::new();
        headers.insert(header::COOKIE, "foo=bar".parse().unwrap());
        assert_eq!(get_cookie(&headers, "baz"), None);
    }

    #[test]
    fn get_cookie_multiple_pairs() {
        let mut headers = http::HeaderMap::new();
        headers.insert(header::COOKIE, "a=1; b=2; c=3".parse().unwrap());
        assert_eq!(get_cookie(&headers, "a"), Some("1"));
        assert_eq!(get_cookie(&headers, "b"), Some("2"));
        assert_eq!(get_cookie(&headers, "c"), Some("3"));
    }

    #[test]
    fn get_cookie_whitespace_trimmed() {
        let mut headers = http::HeaderMap::new();
        headers.insert(header::COOKIE, " foo = bar ".parse().unwrap());
        assert_eq!(get_cookie(&headers, "foo"), Some("bar"));
    }

    #[test]
    fn get_cookie_empty_headers() {
        let headers = http::HeaderMap::new();
        assert_eq!(get_cookie(&headers, "foo"), None);
    }

    #[test]
    fn get_cookie_multiple_cookie_headers() {
        let mut headers = http::HeaderMap::new();
        headers.append(header::COOKIE, "a=1".parse().unwrap());
        headers.append(header::COOKIE, "b=2".parse().unwrap());
        assert_eq!(get_cookie(&headers, "a"), Some("1"));
        assert_eq!(get_cookie(&headers, "b"), Some("2"));
    }

    #[test]
    fn get_cookie_value_with_equals() {
        let mut headers = http::HeaderMap::new();
        headers.insert(header::COOKIE, "token=abc=def".parse().unwrap());
        // split_once on '=' means value is "abc=def"
        assert_eq!(get_cookie(&headers, "token"), Some("abc=def"));
    }

    // -- login_state_cookie_name tests --

    #[test]
    fn cookie_name_secure_root_uses_host_prefix() {
        let name = login_state_cookie_name("abc123", true, "/");
        assert!(name.starts_with("__Host-"));
    }

    #[test]
    fn cookie_name_secure_subpath_uses_secure_prefix() {
        let name = login_state_cookie_name("abc123", true, "/app");
        assert!(name.starts_with("__Secure-"));
    }

    #[test]
    fn cookie_name_insecure_no_prefix() {
        let name = login_state_cookie_name("abc123", false, "/");
        assert!(!name.starts_with("__"));
    }

    #[test]
    fn cookie_name_contains_state() {
        let name = login_state_cookie_name("mystate", true, "/");
        assert!(name.contains("mystate"));
    }

    // -- is_valid_oauth_state tests --

    #[test]
    fn state_accepts_alphanumeric_and_url_safe_chars() {
        assert!(is_valid_oauth_state("abc123"));
        assert!(is_valid_oauth_state("AbC-_xyz"));
    }

    #[test]
    fn state_rejects_empty() {
        assert!(!is_valid_oauth_state(""));
    }

    #[test]
    fn state_rejects_overly_long() {
        let long = "a".repeat(MAX_OAUTH_STATE_LEN + 1);
        assert!(!is_valid_oauth_state(&long));
    }

    #[test]
    fn state_rejects_separators_and_specials() {
        for s in [
            "abc;def", "abc=def", "abc def", "abc\nxyz", "abc/def", "abc+def", "abc.def",
        ] {
            assert!(!is_valid_oauth_state(s), "expected reject: {s:?}");
        }
    }

    #[test]
    fn state_rejects_non_ascii() {
        assert!(!is_valid_oauth_state("café"));
    }
}
