//! Cookie utilities for the login layer.
//!
//! Provides helpers for reading cookies from request headers and constructing
//! login-state cookie names with appropriate security prefixes (`__Host-`,
//! `__Secure-`, or none). Also provides CBOR encoding for the payloads
//! sealed into the session and login-state cookies — CBOR saves ~25–40%
//! over JSON, which matters because session cookies are sent on every
//! authenticated request.
//!
//! If the wire format ever changes, the rollout strategy is the same as for
//! any other key change: in-flight sessions fail to decode, the user is
//! treated as unauthenticated, and the next navigation restarts the login
//! flow. No explicit format-versioning is needed because re-login already
//! recovers gracefully.

use std::{borrow::Cow, sync::Arc, time::Duration};

use base64::{Engine as _, engine::general_purpose::URL_SAFE_NO_PAD};
use http::{HeaderValue, header};
use huskarl::core::crypto::{
    KeyMatchStrength,
    cipher::{AeadCipher, AeadEncryptor as _, AeadUnsealer, AeadV1Cipher, CipherMatch},
};
use serde::{Serialize, de::DeserializeOwned};
use snafu::Snafu;

use crate::{
    config::RoutePath,
    metrics::{DecryptResult, SessionCookieMetrics},
    session::{SessionError, SessionErrorKind},
};

/// The bundle cipher used for every cookie this crate seals: the v1 bundle
/// format over a type-erased AEAD cipher. The format choice is an
/// implementation detail of the cookie layer — builders accept any
/// [`AeadCipher`] and wrap it here.
pub(crate) type SessionCipher = AeadV1Cipher<Arc<dyn AeadCipher>>;

/// Default `Max-Age` for session cookies. 400 days is the practical ceiling
/// most browsers enforce; using it as the default means the cookie is finite
/// (never a true session cookie) but generous enough to never be the binding
/// constraint — the encrypted payload enforces actual session policy.
pub(crate) const DEFAULT_COOKIE_MAX_AGE: Duration = Duration::from_hours(9600);

/// Encodes a cookie payload as CBOR. Used for both the session cookie and
/// the login-state cookie before they are AEAD-sealed and base64-encoded.
pub(crate) fn encode_payload<T: Serialize>(
    value: &T,
) -> Result<Vec<u8>, ciborium::ser::Error<std::io::Error>> {
    let mut bytes = Vec::with_capacity(128);
    ciborium::into_writer(value, &mut bytes)?;
    Ok(bytes)
}

/// Decodes a CBOR cookie payload written by [`encode_payload`].
pub(crate) fn decode_payload<T: DeserializeOwned>(
    bytes: &[u8],
) -> Result<T, ciborium::de::Error<std::io::Error>> {
    ciborium::from_reader(bytes)
}

pub(crate) const DEFAULT_LOGIN_COOKIE_PREFIX: &str = "huskarl_login";

/// Maximum accepted length of an OAuth `state` value. Picks a generous bound
/// (256 bytes) since typical states are 16-64 chars of base64url.
pub(crate) const MAX_OAUTH_STATE_LEN: usize = 256;

/// Returns `true` if `state` is safe to splice into a cookie name: non-empty,
/// within 256 bytes, and composed only of URL-safe base64url characters
/// (`A-Za-z0-9-_`).
///
/// OAuth state is opaque to the spec but generated by us as URL-safe random
/// bytes; this validator rejects attacker-supplied callbacks that try to
/// inject other characters into the cookie name (which would otherwise just
/// silently fail to match a cookie).
#[must_use]
pub fn is_valid_oauth_state(state: &str) -> bool {
    !state.is_empty()
        && state.len() <= MAX_OAUTH_STATE_LEN
        && state
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
}

/// Returns the login-state cookie name for the given OAuth `state` value,
/// applying the appropriate cookie name prefix based on security settings:
///
/// - `__Host-` when `secure` is `true` and `path` is `"/"` (strongest guarantee)
/// - `__Secure-` when `secure` is `true` and `path` is a sub-path
/// - no prefix when `secure` is `false` (e.g. local HTTP development)
///
/// `state` must satisfy [`is_valid_oauth_state`]. In debug builds, an invalid
/// state will assert; in release builds the resulting cookie name may be
/// malformed but no header injection is possible because the name is later
/// formatted through `HeaderValue::from_str`.
#[must_use]
pub fn login_state_cookie_name(state: &str, secure: bool, path: &str, prefix: &str) -> String {
    debug_assert!(
        is_valid_oauth_state(state),
        "login_state_cookie_name called with state that is not URL-safe base64url"
    );
    format!(
        "{}{state}",
        login_state_cookie_name_prefix(secure, path, prefix)
    )
}

/// Returns the name prefix shared by every login-state cookie under the given
/// security settings: `{security_prefix}{prefix}_`. A request cookie whose
/// name starts with this prefix is one of this deployment's in-flight login
/// flows; the rest of the name is the flow's `state` value.
pub(crate) fn login_state_cookie_name_prefix(secure: bool, path: &str, prefix: &str) -> String {
    let security_prefix = if secure {
        if path == "/" { "__Host-" } else { "__Secure-" }
    } else {
        ""
    };
    format!("{security_prefix}{prefix}_")
}

/// Returns the session cookie base name with the `__Host-` prefix applied
/// when the deployment qualifies for it: `secure` set and the cookie scoped
/// to `Path=/` (session cookies never set `Domain`, so those are the only
/// remaining prefix requirements). The prefix makes the browser reject any
/// attempt by a sibling subdomain or a non-secure connection to plant or
/// overwrite the cookie — AEAD already stops forgery, but not an attacker
/// tossing their *own* valid session onto a victim (login CSRF / fixation).
///
/// Names that already carry a security prefix are left untouched, so callers
/// who explicitly chose `__Host-`/`__Secure-` naming keep their exact name.
/// Chunk (`{name}.N`) and kid sidecar (`{name}.kid`) cookies derive from the
/// returned base name, so they inherit the prefix.
pub(crate) fn session_cookie_name(name: &str, secure: bool, path: &str) -> String {
    if secure && path == "/" && !name.starts_with("__Host-") && !name.starts_with("__Secure-") {
        format!("__Host-{name}")
    } else {
        name.to_owned()
    }
}

/// Error returned when a configured session cookie name is rejected.
#[derive(Debug, Clone, PartialEq, Eq, Snafu)]
#[snafu(display("invalid cookie name {name:?}: {reason}"))]
pub struct InvalidCookieName {
    /// The offending name.
    pub name: String,
    /// Why the name was rejected.
    pub reason: &'static str,
}

/// A validated session cookie base name: non-empty and restricted to
/// `[A-Za-z0-9_-]`.
///
/// Carries the cookie-name-safety invariant in the type, so the sinks that
/// interpolate it into `Set-Cookie` — the session cookie and its `{name}.N`
/// chunk / `{name}.kid` sidecar derivatives — never re-check. Establishing the
/// invariant once, at construction, means a new entry point that takes a
/// `CookieName` inherits it for free rather than having to re-validate.
///
/// This is the cookie-name counterpart to
/// [`RoutePath`] (the cookie-`Path` invariant).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CookieName(String);

impl CookieName {
    /// Validates `name` and wraps it.
    ///
    /// Restricts the name to `[A-Za-z0-9_-]`. That is a safe subset of the RFC
    /// 6265 `cookie-name` token (it excludes every separator — `;`, `=`, space,
    /// etc. — that would corrupt or inject into the `Set-Cookie` header), and
    /// matches the rule on `login_cookie_prefix`. It also excludes `.`, which
    /// the chunk (`{name}.N`) and kid-sidecar (`{name}.kid`) cookies use as a
    /// namespace separator — so a base name can never collide with those.
    ///
    /// # Errors
    ///
    /// Returns [`InvalidCookieName`] naming the offending value and why it was
    /// rejected.
    pub fn new(name: impl Into<String>) -> Result<Self, InvalidCookieName> {
        let name = name.into();
        if name.is_empty() {
            return Err(InvalidCookieName {
                name,
                reason: "must not be empty",
            });
        }
        if !name
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'-')
        {
            return Err(InvalidCookieName {
                name,
                reason: "must contain only ASCII letters, digits, '_', or '-'",
            });
        }
        Ok(Self(name))
    }

    /// The validated name as a string slice.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for CookieName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl AsRef<str> for CookieName {
    fn as_ref(&self) -> &str {
        &self.0
    }
}

// `TryFrom`, not `From`: validation is fallible. Mirrors [`CookieName::new`]
// for `?`/`try_into()` callers.
impl TryFrom<String> for CookieName {
    type Error = InvalidCookieName;
    fn try_from(name: String) -> Result<Self, Self::Error> {
        Self::new(name)
    }
}

impl TryFrom<&str> for CookieName {
    type Error = InvalidCookieName;
    fn try_from(name: &str) -> Result<Self, Self::Error> {
        Self::new(name)
    }
}

// Enables `"session".parse::<CookieName>()` and inference at call sites that
// expect a `CookieName` (e.g. the `cookie_name` builder setters).
impl std::str::FromStr for CookieName {
    type Err = InvalidCookieName;
    fn from_str(name: &str) -> Result<Self, Self::Err> {
        Self::new(name)
    }
}

/// Builds the standard cookie attribute string for session cookies.
///
/// Returns `"HttpOnly; SameSite=Lax; Path={path}; Secure"` (or without
/// `Secure` when `secure` is `false`).
#[must_use]
pub fn cookie_attrs(secure: bool, path: &str) -> String {
    let secure = if secure { "; Secure" } else { "" };
    format!("HttpOnly; SameSite=Lax; Path={path}{secure}")
}

/// The shared cookie-sealing machinery behind both built-in session stores
/// ([`CookieSessionStore`](crate::CookieSessionStore) and
/// [`StoreBackedSessionStore`](crate::StoreBackedSessionStore)).
///
/// Both stores seal a value (a chunked session payload, or a UUID pointer)
/// under AEAD into a security-prefixed cookie, emit the kid sidecar, and record
/// the same encrypt/decrypt metrics. Centralizing that state here keeps the two
/// stores from drifting — a fix to a cookie security attribute or the kid
/// sidecar lands in one place rather than two.
pub(crate) struct CookieSealer {
    /// The v1-bundle cipher used to seal/unseal cookie values.
    pub(crate) cipher: SessionCipher,
    /// The raw cipher behind [`cipher`](Self::cipher), retained so a store can
    /// hand it back via
    /// [`SessionDriver::session_aead_cipher`](crate::SessionDriver::session_aead_cipher)
    /// without re-wrapping it in the v1 bundle envelope.
    pub(crate) aead: Arc<dyn AeadCipher>,
    /// The configured cookie name, before any security prefix is applied.
    /// Retained so [`apply_secure`](Self::apply_secure) can recompute
    /// `cookie_name` once the engine supplies the deployment's `secure` flag.
    raw_cookie_name: CookieName,
    /// The security-prefixed cookie name actually emitted on the wire.
    pub(crate) cookie_name: String,
    /// Whether the deployment is HTTPS (drives the `Secure` attribute and the
    /// `__Host-`/`__Secure-` name prefix).
    pub(crate) secure: bool,
    cookie_path: RoutePath,
    max_age: Duration,
    metrics: Option<Arc<dyn SessionCookieMetrics>>,
}

impl CookieSealer {
    /// Wraps `cipher` in the v1 bundle format and derives the initial
    /// (secure-by-default) cookie name. `secure` is re-stamped by the engine
    /// via [`apply_secure`](Self::apply_secure) once it knows the `base_url`
    /// scheme; until then the safe choice (secure, `__Host-` prefix) is used.
    pub(crate) fn new(
        cipher: Arc<dyn AeadCipher>,
        cookie_name: CookieName,
        cookie_path: RoutePath,
        max_age: Duration,
        metrics: Option<Arc<dyn SessionCookieMetrics>>,
    ) -> Self {
        let secure = true;
        let raw_cookie_name = cookie_name;
        let cookie_name =
            session_cookie_name(raw_cookie_name.as_str(), secure, cookie_path.as_str());
        Self {
            aead: cipher.clone(),
            cipher: AeadV1Cipher::new(cipher),
            raw_cookie_name,
            cookie_name,
            secure,
            cookie_path,
            max_age,
            metrics,
        }
    }

    /// The active key's identity, if it has one. See
    /// [`AeadEncryptor::key_id`](huskarl::core::crypto::cipher::AeadEncryptor::key_id).
    pub(crate) fn key_id(&self) -> Option<Cow<'_, str>> {
        self.cipher.key_id()
    }

    /// Re-derives `cookie_name` for the deployment's real `secure` flag.
    pub(crate) fn apply_secure(&mut self, secure: bool) {
        self.secure = secure;
        self.cookie_name = session_cookie_name(
            self.raw_cookie_name.as_str(),
            secure,
            self.cookie_path.as_str(),
        );
    }

    /// Cookie attributes without `Max-Age` — used for clears (which append
    /// their own `Max-Age=0`).
    pub(crate) fn base_cookie_attrs(&self) -> String {
        cookie_attrs(self.secure, self.cookie_path.as_str())
    }

    /// Full cookie attributes including this store's configured `Max-Age`.
    pub(crate) fn cookie_attrs(&self) -> String {
        format!(
            "{}; Max-Age={}",
            self.base_cookie_attrs(),
            self.max_age.as_secs()
        )
    }

    /// Builds the `Set-Cookie` for the kid sidecar. When `kid` is `Some`, the
    /// value is the base64url-encoded identity; when `None`, a `Max-Age=0`
    /// clear is emitted so a sidecar set under a previous (identity-bearing)
    /// key doesn't linger after operators switch to a key source with no
    /// natural identity.
    pub(crate) fn build_kid_header(&self, kid: Option<&str>) -> Result<HeaderValue, SessionError> {
        let name = kid_cookie_name(&self.cookie_name);
        let value = match kid {
            Some(k) => format!("{name}={}; {}", encode_kid(k), self.cookie_attrs()),
            None => format!("{name}=; {}; Max-Age=0", self.base_cookie_attrs()),
        };
        HeaderValue::from_str(&value).map_err(|e| SessionError::new(SessionErrorKind::Store, e))
    }

    /// Records an encrypt event (active key id) if metrics are configured.
    pub(crate) fn record_encrypt(&self, kid: Option<&str>) {
        if let Some(m) = &self.metrics {
            m.record_encrypt(&self.cookie_name, kid);
        }
    }

    /// Records a decrypt outcome if metrics are configured, after bounding the
    /// client-supplied kid to a configured key (or `"unknown"`) so it can't
    /// inflate label cardinality.
    pub(crate) fn record_decrypt(&self, kid: Option<&str>, result: &DecryptResult) {
        let label = normalize_kid_label(&*self.aead, &self.cookie_name, kid);
        if let Some(m) = &self.metrics {
            m.record_decrypt(&self.cookie_name, label, result);
        }
    }
}

/// Suffix appended to a session cookie's base name to form its kid sidecar
/// cookie name. The sidecar carries the active key's identity (as reported by
/// the sealer) base64url-encoded; the unsealer uses it as a search-space hint
/// so multi-key decrypt doesn't have to trial every candidate.
///
/// The sidecar is not security-bearing: tampering or absence just degrades to
/// trial-decrypt across all configured keys, which is the safe baseline. The
/// AEAD seal remains the sole authenticity gate. The hint-not-filter property
/// is enforced by [`unseal_with_kid_fallback`], because the underlying
/// multi-key cipher treats an unmatched kid as a hard "no matching key"
/// failure rather than falling back on its own.
pub(crate) const KID_COOKIE_SUFFIX: &str = ".kid";

/// Unseals `bundle`, treating the kid sidecar's `cipher_match` as a hint
/// rather than a filter: if unsealing under the hint fails, retry once across
/// all configured keys.
///
/// The sidecar is browser-held and unauthenticated, so it can be stale or
/// tampered with independently of the (AEAD-sealed) payload it accompanies. A
/// wrong hint must not lock out a session that one of the configured keys can
/// authenticate — absence of the hint is the safe baseline, and a bad hint
/// must degrade to exactly that. The happy path still pays only one unseal;
/// the retry happens only on failure, where a second decrypt attempt is noise.
pub(crate) async fn unseal_with_kid_fallback(
    unsealer: &impl AeadUnsealer,
    cipher_match: Option<&CipherMatch<'_>>,
    bundle: &[u8],
    aad: &[u8],
) -> Option<Vec<u8>> {
    if let Some(m) = cipher_match
        && let Ok(plaintext) = unsealer.unseal(Some(m), bundle, aad).await
    {
        return Some(plaintext);
    }
    unsealer.unseal(None, bundle, aad).await.ok()
}

/// Returns the sidecar cookie name for the given session cookie base name.
#[must_use]
pub(crate) fn kid_cookie_name(base_name: &str) -> String {
    format!("{base_name}{KID_COOKIE_SUFFIX}")
}

/// Reads the kid sidecar cookie associated with `base_name` and returns the
/// decoded identity string, or `None` if the cookie is missing, not valid
/// base64url, or not valid UTF-8. Any failure mode is treated the same: the
/// unsealer falls back to trial-decrypt.
pub(crate) fn get_kid_cookie(headers: &http::HeaderMap, base_name: &str) -> Option<String> {
    let name = kid_cookie_name(base_name);
    let encoded = get_cookie(headers, &name)?;
    let bytes = URL_SAFE_NO_PAD.decode(encoded).ok()?;
    String::from_utf8(bytes).ok()
}

/// Returns the base64url encoding of `identity`, used as the kid sidecar
/// cookie's value. Identities can contain characters outside the cookie-value
/// charset (e.g. `:` in KMS ARNs), so they're always encoded.
#[must_use]
pub(crate) fn encode_kid(identity: &str) -> String {
    URL_SAFE_NO_PAD.encode(identity.as_bytes())
}

/// Normalizes a kid read from the (client-supplied) sidecar cookie into a
/// bounded metrics label.
///
/// The sidecar is attacker-controllable — anyone can send an arbitrary
/// `{name}.kid` request cookie — so passing it through verbatim would let
/// crafted values inflate metrics label cardinality without limit (a TSDB
/// `DoS`). Instead the value is kept only when it names a configured key
/// (`cipher_match` reports an exact [`KeyMatchStrength::ByKeyId`]), and
/// collapsed to `"unknown"` otherwise — the same closed-set discipline
/// [`normalize_as_error`](crate::normalize_as_error) applies to the
/// attacker-suppliable authorization-server error code. `ByAlgorithm` does not
/// count: it fires for keyless / no-kid ciphers on *any* input, which would
/// leave the label unbounded.
///
/// An unmatched kid is logged at debug level. A one-off is just a stale or
/// forged cookie; a *persistent* unmatched kid can flag a key retired while
/// sessions sealed under it are still in flight.
pub(crate) fn normalize_kid_label<'a>(
    cipher: &dyn AeadCipher,
    cookie_name: &str,
    kid: Option<&'a str>,
) -> Option<&'a str> {
    let k = kid?;
    let m = CipherMatch::builder().kid(k).build();
    if matches!(cipher.cipher_match(&m), Some(KeyMatchStrength::ByKeyId)) {
        Some(k)
    } else {
        log::debug!("session cookie {cookie_name}: sidecar kid {k:?} matches no configured key");
        Some("unknown")
    }
}

/// Extracts a cookie value by name from request headers.
///
/// This is a utility function for [`SessionDriver`](crate::session::SessionDriver)
/// implementations that need to read cookies from request headers.
pub fn get_cookie<'a>(headers: &'a http::HeaderMap, name: &str) -> Option<&'a str> {
    for value in headers.get_all(header::COOKIE) {
        let Ok(s) = value.to_str() else { continue };
        for pair in s.split(';') {
            if let Some((k, v)) = pair.trim().split_once('=')
                && k.trim() == name
            {
                return Some(v.trim());
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn get_cookie_present() {
        let mut headers = http::HeaderMap::new();
        headers.insert(header::COOKIE, "foo=bar".parse().unwrap());
        assert_eq!(get_cookie(&headers, "foo"), Some("bar"));
    }

    #[test]
    fn get_cookie_missing() {
        let mut headers = http::HeaderMap::new();
        headers.insert(header::COOKIE, "foo=bar".parse().unwrap());
        assert_eq!(get_cookie(&headers, "baz"), None);
    }

    #[test]
    fn get_cookie_multiple_pairs() {
        let mut headers = http::HeaderMap::new();
        headers.insert(header::COOKIE, "a=1; b=2; c=3".parse().unwrap());
        assert_eq!(get_cookie(&headers, "a"), Some("1"));
        assert_eq!(get_cookie(&headers, "b"), Some("2"));
        assert_eq!(get_cookie(&headers, "c"), Some("3"));
    }

    #[test]
    fn get_cookie_whitespace_trimmed() {
        let mut headers = http::HeaderMap::new();
        headers.insert(header::COOKIE, " foo = bar ".parse().unwrap());
        assert_eq!(get_cookie(&headers, "foo"), Some("bar"));
    }

    #[test]
    fn get_cookie_empty_headers() {
        let headers = http::HeaderMap::new();
        assert_eq!(get_cookie(&headers, "foo"), None);
    }

    #[test]
    fn get_cookie_multiple_cookie_headers() {
        let mut headers = http::HeaderMap::new();
        headers.append(header::COOKIE, "a=1".parse().unwrap());
        headers.append(header::COOKIE, "b=2".parse().unwrap());
        assert_eq!(get_cookie(&headers, "a"), Some("1"));
        assert_eq!(get_cookie(&headers, "b"), Some("2"));
    }

    #[test]
    fn get_cookie_value_with_equals() {
        let mut headers = http::HeaderMap::new();
        headers.insert(header::COOKIE, "token=abc=def".parse().unwrap());
        // split_once on '=' means value is "abc=def"
        assert_eq!(get_cookie(&headers, "token"), Some("abc=def"));
    }

    // -- login_state_cookie_name tests --

    #[test]
    fn cookie_name_secure_root_uses_host_prefix() {
        let name = login_state_cookie_name("abc123", true, "/", DEFAULT_LOGIN_COOKIE_PREFIX);
        assert!(name.starts_with("__Host-"));
    }

    #[test]
    fn cookie_name_secure_subpath_uses_secure_prefix() {
        let name = login_state_cookie_name("abc123", true, "/app", DEFAULT_LOGIN_COOKIE_PREFIX);
        assert!(name.starts_with("__Secure-"));
    }

    #[test]
    fn cookie_name_insecure_no_prefix() {
        let name = login_state_cookie_name("abc123", false, "/", DEFAULT_LOGIN_COOKIE_PREFIX);
        assert!(!name.starts_with("__"));
    }

    #[test]
    fn cookie_name_is_prefix_plus_state() {
        for (secure, path) in [(true, "/"), (true, "/app"), (false, "/")] {
            let name = login_state_cookie_name("abc123", secure, path, DEFAULT_LOGIN_COOKIE_PREFIX);
            let prefix = login_state_cookie_name_prefix(secure, path, DEFAULT_LOGIN_COOKIE_PREFIX);
            assert_eq!(name, format!("{prefix}abc123"));
        }
    }

    #[test]
    fn cookie_name_contains_state() {
        let name = login_state_cookie_name("mystate", true, "/", DEFAULT_LOGIN_COOKIE_PREFIX);
        assert!(name.contains("mystate"));
    }

    // -- is_valid_oauth_state tests --

    #[test]
    fn state_accepts_alphanumeric_and_url_safe_chars() {
        assert!(is_valid_oauth_state("abc123"));
        assert!(is_valid_oauth_state("AbC-_xyz"));
    }

    #[test]
    fn state_rejects_empty() {
        assert!(!is_valid_oauth_state(""));
    }

    #[test]
    fn state_rejects_overly_long() {
        let long = "a".repeat(MAX_OAUTH_STATE_LEN + 1);
        assert!(!is_valid_oauth_state(&long));
    }

    #[test]
    fn state_rejects_separators_and_specials() {
        for s in [
            "abc;def", "abc=def", "abc def", "abc\nxyz", "abc/def", "abc+def", "abc.def",
        ] {
            assert!(!is_valid_oauth_state(s), "expected reject: {s:?}");
        }
    }

    #[test]
    fn state_rejects_non_ascii() {
        assert!(!is_valid_oauth_state("café"));
    }

    // -- session_cookie_name tests --

    #[test]
    fn session_cookie_name_prefixes_secure_root() {
        assert_eq!(session_cookie_name("sess", true, "/"), "__Host-sess");
    }

    #[test]
    fn session_cookie_name_skips_insecure() {
        assert_eq!(session_cookie_name("sess", false, "/"), "sess");
    }

    #[test]
    fn session_cookie_name_skips_subpath() {
        assert_eq!(session_cookie_name("sess", true, "/app"), "sess");
    }

    #[test]
    fn session_cookie_name_keeps_existing_prefix() {
        assert_eq!(session_cookie_name("__Host-sess", true, "/"), "__Host-sess");
        assert_eq!(
            session_cookie_name("__Secure-sess", true, "/"),
            "__Secure-sess"
        );
    }

    // -- CookieName tests --

    #[test]
    fn cookie_name_new_accepts_and_rejects() {
        assert_eq!(
            CookieName::new("huskarl_session").unwrap().as_str(),
            "huskarl_session"
        );
        assert_eq!(
            CookieName::new("__Host-sess").unwrap().as_str(),
            "__Host-sess"
        );
        assert_eq!(CookieName::new("").unwrap_err().reason, "must not be empty");
        // Separators that would corrupt/inject into Set-Cookie.
        assert!(CookieName::new("bad;name").is_err());
        assert!(CookieName::new("a=b").is_err());
        assert!(CookieName::new("has space").is_err());
        // `.` is reserved for the chunk/kid sidecar namespace.
        assert!(CookieName::new("base.kid").is_err());
    }

    #[test]
    fn cookie_name_try_from() {
        assert!(CookieName::try_from("ok_name").is_ok());
        assert!(CookieName::try_from("bad;x".to_owned()).is_err());
        let n: CookieName = "scoped".try_into().unwrap();
        assert_eq!(n.as_str(), "scoped");
    }

    // -- kid sidecar tests --

    #[test]
    fn kid_cookie_name_suffixes_base() {
        assert_eq!(kid_cookie_name("huskarl_session"), "huskarl_session.kid");
    }

    #[test]
    fn get_kid_cookie_decodes_present_value() {
        let mut headers = http::HeaderMap::new();
        let encoded = encode_kid("arn:aws:kms:us-east-1:111:key/abc");
        headers.insert(
            header::COOKIE,
            format!("huskarl_session.kid={encoded}").parse().unwrap(),
        );
        assert_eq!(
            get_kid_cookie(&headers, "huskarl_session").as_deref(),
            Some("arn:aws:kms:us-east-1:111:key/abc")
        );
    }

    #[test]
    fn get_kid_cookie_absent_returns_none() {
        let headers = http::HeaderMap::new();
        assert_eq!(get_kid_cookie(&headers, "huskarl_session"), None);
    }

    #[test]
    fn get_kid_cookie_invalid_base64_returns_none() {
        let mut headers = http::HeaderMap::new();
        headers.insert(
            header::COOKIE,
            "huskarl_session.kid=!!!notbase64!!!".parse().unwrap(),
        );
        assert_eq!(get_kid_cookie(&headers, "huskarl_session"), None);
    }

    #[test]
    fn get_kid_cookie_invalid_utf8_returns_none() {
        let mut headers = http::HeaderMap::new();
        // base64url of [0xff, 0xfe, 0xfd] — valid base64 but not valid UTF-8.
        let bad = URL_SAFE_NO_PAD.encode([0xff_u8, 0xfe, 0xfd]);
        headers.insert(
            header::COOKIE,
            format!("huskarl_session.kid={bad}").parse().unwrap(),
        );
        assert_eq!(get_kid_cookie(&headers, "huskarl_session"), None);
    }
}
